import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
              "on-background": "#272c51",
              "on-primary-fixed": "#000000",
              "tertiary-dim": "#7f2d7f",
              "tertiary-container": "#f395ee",
              "secondary-fixed-dim": "#b9bfff",
              "on-error": "#ffefee",
              "on-surface": "#272c51",
              "on-tertiary-container": "#5e0b61",
              "inverse-primary": "#5c8bff",
              "outline-variant": "#a6aad7",
              "primary-fixed-dim": "#618eff",
              "secondary-dim": "#3744ab",
              "surface-container-low": "#f1efff",
              "secondary-container": "#caceff",
              "primary": "#0053cd",
              "tertiary-fixed": "#f395ee",
              "surface-bright": "#f8f5ff",
              "on-secondary-container": "#2e3ba2",
              "on-tertiary-fixed": "#3b003e",
              "primary-fixed": "#789dff",
              "on-error-container": "#570008",
              "on-surface-variant": "#545981",
              "on-tertiary-fixed-variant": "#69186b",
              "error": "#b31b25",
              "surface-container-highest": "#d8daff",
              "surface-tint": "#0053cd",
              "on-secondary-fixed-variant": "#3945ac",
              "on-secondary": "#f3f1ff",
              "error-dim": "#9f0519",
              "surface-dim": "#ced1ff",
              "background": "#f8f5ff",
              "on-primary": "#f1f2ff",
              "primary-dim": "#0048b5",
              "outline": "#6f749e",
              "surface": "#f8f5ff",
              "surface-container": "#e6e6ff",
              "surface-container-lowest": "#ffffff",
              "inverse-on-surface": "#969ac6",
              "surface-container-high": "#dfe0ff",
              "secondary": "#4451b7",
              "inverse-surface": "#05092f",
              "primary-container": "#789dff",
              "error-container": "#fb5151",
              "surface-variant": "#d8daff",
              "tertiary": "#8c3a8c",
              "on-secondary-fixed": "#17258f",
              "secondary-fixed": "#caceff",
              "on-primary-container": "#001f57",
              "on-tertiary": "#ffeef9",
              "on-primary-fixed-variant": "#00276b",
              "tertiary-fixed-dim": "#e488df"
            },
            fontFamily: {
              "headline": ["Manrope", ...defaultTheme.fontFamily.sans],
              "body": ["Inter", ...defaultTheme.fontFamily.sans],
              "label": ["Inter", ...defaultTheme.fontFamily.sans],
              "sans": ["Inter", ...defaultTheme.fontFamily.sans],
            },
            borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
        },
    },

    plugins: [forms, require('daisyui')],
};
